"""Configuration constants for the YT Music Remote server."""

# WebSocket server
WS_HOST = "0.0.0.0"
WS_PORT = 8765

# Authentication
AUTH_PIN = "1234"  # Displayed in terminal on start, user enters on phone

# State broadcast interval (seconds)
STATE_BROADCAST_INTERVAL = 1.0

# ytmusicapi
YTMUSIC_AUTH_FILE = "oauth.json"  # Generated by `ytmusicapi oauth`

# mpv defaults
MPV_DEFAULT_VOLUME = 70

# yt-dlp
YTDLP_FORMAT = "bestaudio"
